Repository Stendhalsynd/career-up-front, pull requests merged in 2023-11, with the labels that each got.

#12 feat: Input 컴포넌트
  .github/pull_request_template.md
  src/components/atoms/Input/index.stories.tsx
  src/components/atoms/Input/index.tsx
  src/components/atoms/Text/index.tsx
  src/themes/colors.ts
Labels: feat

#15 feat: TextArea 컴포넌트 생성
  src/components/molecules/TextArea/index.stories.tsx
  src/components/molecules/TextArea/index.tsx
Labels: feat

#16 Feat/#10 Avatar 컴포넌트 생성
  .storybook/main.ts
  .storybook/public/images/sample/img_avatar.svg
  next.config.js
  package-lock.json
  package.json
  public/assets/image/img_avatar.svg
  src/app/page.tsx
  src/components/atoms/Avatar/index.stories.tsx
  src/components/atoms/Avatar/index.tsx
  src/components/molecules/TextArea/index.tsx
Labels: feat

#20 feat/#19 icon storybook 추가
  .storybook/public/assets/icon/icon_bussiness_bag.svg
  .storybook/public/assets/icon/icon_desktop.svg
  .storybook/public/assets/icon/icon_warning.svg
  .storybook/public/assets/image/sample/img_avatar.svg
  src/components/atoms/Avatar/index.stories.tsx
  src/components/atoms/Avatar/index.tsx
  src/components/atoms/Icon/index.stories.tsx
Labels: feat

#22 feat/#21 storybook viewport 설정, 절대경로 설정, Box 컴포넌트에 maxWidth, maxHeight 추가
  .storybook/preview.ts
  src/app/page.tsx
  src/components/atoms/index.ts
  src/components/layout/Box/index.tsx
  src/components/layout/index.ts
  src/components/molecules/index.ts
Labels: feat

#25 feat/#24 Label 컴포넌트 생성
  src/app/page.tsx
  src/components/atoms/Text/index.tsx
  src/components/molecules/Label/index.stories.tsx
  src/components/molecules/Label/index.tsx
Labels: feat

#29 feat/#28-recoil 설정
  README.md
  package-lock.json
  package.json
  recoil.ts
Labels: feat

#32 Feat/#6 header
  .eslintrc.json
  README.md
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/atoms/Icon/index.tsx
  src/components/atoms/Logo/index.tsx
  src/components/atoms/Picture/index.tsx
  src/components/layout/Box/index.tsx
  src/components/layout/Flex/index.tsx
  src/components/molecules/Header/index.tsx
  tsconfig.json
Labels: feat

#35 feat/#26-dropdownButton
  .storybook/public/assets/icon/icon_dropdown.svg
  next.config.js
  package-lock.json
  package.json
  recoil.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/atoms/Icon/index.tsx
  src/components/atoms/Logo/index.tsx
  src/components/atoms/Text/index.tsx
  src/components/layout/Box/index.tsx
  src/components/molecules/DropdownButton/index.stories.tsx
  src/components/molecules/DropdownButton/index.tsx
  src/components/molecules/index.ts
  src/lib/registry.tsx
  src/lib/theme.tsx
  src/lib/useMediaQuery.tsx
Labels: feat

#38 Mod/#37 button
  .storybook/preview.ts
  src/app/page.tsx
  src/components/molecules/Button/HyperLinkButton.tsx
  src/components/molecules/Button/NicknameButton.tsx
  src/components/molecules/Button/RequestButton.tsx
  src/components/molecules/Button/SelectButton.tsx
  src/components/molecules/Button/StatusButton.tsx
  src/components/molecules/Button/TagButton.tsx
  src/components/molecules/Button/index.tsx
  src/components/molecules/Input/index.tsx
  src/components/molecules/SearchInput/index.stories.tsx
  src/components/organisms/Login/index.tsx
  src/components/organisms/Signup/index.tsx
Labels: feat, mod

#41 feat/#30-workerInfoCard, chatInfoCard 생성
  src/components/atoms/Text/index.tsx
  src/components/molecules/Button/index.tsx
  src/components/molecules/Label/index.tsx
  src/components/organisms/ChatInfoCard/index.tsx
  src/components/organisms/WorkerInfoCard/index.tsx
  src/themes/fontSizes.ts
Labels: bug, feat

#46 feat/#45 layout 컴포넌트 생성
  src/components/molecules/index.ts
  src/components/templates/Layout/index.tsx
Labels: feat

#48 feat/#47-useMediaQuery
  .eslintrc.json
  src/components/atoms/Logo/index.tsx
  src/lib/useMediaQuery.tsx
Labels: feat

#52 Feat/#50 storybook chromatic
  .github/workflows/chromatic.yml
  .gitignore
  README.md
  build-storybook.log
  package-lock.json
  package.json
  src/components/atoms/Picture/index.stories.tsx
Labels: bug, feat

#53 feat/#49-storybook autodocs
  package.json
  src/components/atoms/Avatar/index.stories.tsx
  src/components/atoms/Icon/index.stories.tsx
  src/components/atoms/Icon/index.tsx
  src/components/atoms/Logo/index.stories.tsx
  src/components/atoms/Text/index.stories.ts
  src/components/molecules/DropdownButton/index.stories.tsx
  src/components/molecules/Header/index.stories.tsx
  src/components/molecules/Input/index.stories.tsx
  src/components/molecules/Label/index.stories.tsx
  src/components/molecules/SearchInput/index.stories.tsx
  src/components/molecules/TextArea/index.stories.tsx
  src/components/organisms/Login/index.stories.tsx
  src/components/organisms/Signup/index.stories.tsx
Labels: feat

#54 mod/#42-chatInfoCard 수정
  src/app/page.tsx
  src/components/atoms/Icon/index.tsx
  src/components/layout/Box/index.tsx
  src/components/organisms/AlertContainer/index.stories.tsx
  src/components/organisms/AlertContainer/index.tsx
  src/components/organisms/ChatInfoCard/index.stories.tsx
  src/components/organisms/ChatInfoCard/index.tsx
  src/components/organisms/TodayChatInfo/index.stories.tsx
  src/components/organisms/TodayChatInfo/index.tsx
  src/components/organisms/WorkerInfoCard/index.stories.tsx
  src/components/organisms/WorkerInfoCard/index.tsx
Labels: feat

#56 Feat/#43 job seeker my page
  public/assets/image/img_supertoroid2.svg
  src/app/page.tsx
  src/app/users/[id]/page.tsx
  src/components/atoms/Avatar/index.stories.tsx
  src/components/atoms/Avatar/index.tsx
  src/components/atoms/Picture/index.tsx
  src/components/atoms/Text/index.stories.ts
  src/components/layout/Box/index.tsx
  src/components/molecules/Button/SelectButton.tsx
  src/components/molecules/DropdownButton/index.stories.tsx
  src/components/molecules/DropdownButton/index.tsx
  src/components/molecules/Input/index.tsx
  src/components/molecules/Label/index.stories.tsx
  src/components/molecules/Label/index.tsx
  src/components/organisms/AlertContainer/index.tsx
  src/components/organisms/ChatInfoCard/index.tsx
  src/components/organisms/TodayChatInfo/index.tsx
  src/components/templates/MyPageLayout/index.tsx
Labels: feat

#61 feat/#58-add MentoSearch component
  package.json
  src/app/page.tsx
  src/components/molecules/DropdownButton/index.tsx
  src/components/molecules/SearchInput/index.tsx
  src/components/organisms/FilterModal/index.tsx
  src/components/organisms/MentoSearch/index.tsx
  src/components/organisms/index.ts
Labels: feat

#64 feat: MeetingApply 페이지 생성
  README.md
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/meeting/page.tsx
  src/components/molecules/Button/index.stories.tsx
  src/components/molecules/Calendar/index.tsx
  src/components/templates/MeetingLayout/index.tsx
  src/lib/mui.tsx
Labels: feat

#65 Feat/#62 login, signup page
  src/app/login/page.tsx
  src/app/meeting/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
  src/components/organisms/Login/index.tsx
  src/components/organisms/MentoSearch/index.stories.tsx
  src/components/organisms/MentoSearch/index.tsx
  src/components/organisms/Signup/index.tsx
  src/components/templates/LoginSignupLayout/index.tsx
  src/components/templates/MyPageLayout/index.tsx
Labels: feat

#67 feat/#66 workerInfo 페이지 생성
  public/assets/image/img_computer.svg
  src/app/users/[id]/edit/page.tsx
  src/app/workers/[id]/edit/page.tsx
  src/app/workers/[id]/info/page.tsx
  src/components/molecules/Button/index.stories.tsx
Labels: feat

#69 feat/#68 WorkerInfoList 페이지 UI 생성
  public/assets/image/img_pill.svg
  public/assets/image/img_supertoroid2.svg
  src/app/search/page.tsx
  src/components/organisms/WorkerInfoCard/index.tsx
  src/components/templates/WorkerInfoListLayout/index.tsx
Labels: feat

#74 feat/#71 openVidu 기본적인 1:1 화상 채팅 테스트 설정
  package-lock.json
  package.json
  src/app/chat/page.tsx
  src/chat/App.tsx
  src/chat/OvVideo.tsx
  src/chat/UserVideo.css
  src/chat/UserVideoComponent.tsx
  src/chat/registerServiceWorker.tsx
  src/chats/App.css
  src/chats/App.jsx
  src/chats/Temp.tsx
  src/chats/assets/img/favicon.ico
  src/chats/assets/img/openvidu_globe_bg_transp_cropped.png
  src/chats/assets/img/openvidu_grey_bg_transp_cropped.png
  src/chats/assets/img/openvidu_logo.png
  src/chats/assets/img/openvidu_vert_white_bg_trans.png
  src/chats/assets/img/openvidu_vert_white_bg_trans_cropped.png
  src/chats/assets/img/react-logo.svg
  src/chats/index.css
  src/chats/index.js
  src/chats/registerServiceWorker.js
  src/components/molecules/DropdownButton/index.tsx
  tsconfig.json
Labels: feat

#76 hotfix: port 번호 이슈 체크
  src/chat/App.tsx
Labels: bug

#79 feat/#70-모바일 버전 메인페이지 생성
  public/assets/image/img_roundcube1.svg
  public/assets/image/img_roundcube2.svg
  public/assets/image/img_supertoroid1.svg
  public/assets/image/img_supertoroid3.svg
  src/app/page.tsx
  src/components/atoms/Text/index.tsx
  src/components/layout/Flex/index.tsx
  src/components/molecules/Button/HyperLinkButton.tsx
  src/components/organisms/Main/ChatInfoContainer/index.tsx
  src/components/organisms/Main/IntroTextContainer/index.tsx
  src/components/organisms/Main/ProcessInfoContainer/index.tsx
  src/components/organisms/Main/PromoteTextContainer/index.tsx
  src/components/organisms/Main/WorkerInfoContainer/index.tsx
  src/components/organisms/WorkerInfoCard/index.tsx
  src/components/templates/MainLayout/MainBlackBackgroundLayout/index.tsx
  src/components/templates/MainLayout/MainBlueBackgroundLayout/index.tsx
  src/components/templates/MainLayout/index.tsx
Labels: feat

#80 Feat/#73 login api
  package-lock.json
  package.json
  src/components/molecules/Button/HyperLinkButton.tsx
  src/components/molecules/Button/SelectButton.tsx
  src/components/molecules/Button/index.stories.tsx
  src/components/organisms/Login/index.tsx
  src/components/organisms/Signup/index.tsx
Labels: feat

#82 feat/#70-메인페이지 생성
  src/components/molecules/Button/HyperLinkButton.tsx
  src/components/organisms/Main/ChatInfoContainer/index.tsx
  src/components/organisms/Main/IntroTextContainer/index.tsx
  src/components/organisms/Main/ProcessInfoContainer/index.tsx
  src/components/organisms/Main/PromoteTextContainer/index.tsx
  src/components/organisms/Main/WorkerInfoContainer/index.tsx
  src/components/organisms/WorkerInfoCard/index.tsx
  src/components/templates/LoginSignupLayout/index.tsx
  src/components/templates/MainLayout/MainBlackBackgroundLayout/index.tsx
  src/components/templates/MainLayout/MainBlueBackgroundLayout/index.tsx
Labels: feat

#85 feat: openvidu ToolBar 컴포넌트 UI 커스텀
  nginx.conf
  package-lock.json
  package.json
  src/app/chat/page.tsx
  src/app/layout.tsx
  src/chat/App.tsx
  src/chat/src/assets/images/openvidu_logo.png
  src/chat/src/components/VideoRoomComponent.css
  src/chat/src/components/VideoRoomComponent.js
  src/chat/src/components/chat/ChatComponent.css
  src/chat/src/components/chat/ChatComponent.js
  src/chat/src/components/dialog-extension/DialogExtension.css
  src/chat/src/components/dialog-extension/DialogExtension.js
  src/chat/src/components/stream/OvVideo.js
  src/chat/src/components/stream/StreamComponent.css
  src/chat/src/components/stream/StreamComponent.js
  src/chat/src/components/toolbar/ToolbarComponent.css
  src/chat/src/components/toolbar/ToolbarComponent.js
  src/chat/src/index.css
  src/chat/src/layout/openvidu-layout.js
  src/chat/src/library-copy.js
  src/chat/src/models/user-model.js
  src/chat/src/registerServiceWorker.js
  src/chats/App.css
  src/chats/App.jsx
  src/chats/Temp.tsx
  src/chats/assets/img/favicon.ico
  src/chats/assets/img/openvidu_globe_bg_transp_cropped.png
  src/chats/assets/img/openvidu_grey_bg_transp_cropped.png
  src/chats/assets/img/openvidu_logo.png
  src/chats/assets/img/openvidu_vert_white_bg_trans.png
  src/chats/assets/img/openvidu_vert_white_bg_trans_cropped.png
  src/chats/assets/img/react-logo.svg
  src/chats/index.css
  src/chats/index.js
  src/lib/serviceWorker.tsx
Labels: feat
