Repository Stendhalsynd/career-up-front, pull requests merged in 2023-12, with the labels that each got.

#89 feat/#86 채팅방 입장하기
  README.md
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/seekerChat/page.tsx
  src/app/workerChat/page.tsx
  src/chat/App.tsx
  src/chat/src/components/VideoRoomComponent.js
  src/components/molecules/Button/HyperLinkButton.tsx
  src/components/organisms/TodayChatInfo/index.tsx
  src/lib/recoil.tsx
  src/lib/useRequest.ts
  src/types/data.d.ts
  src/utils/state.ts
Labels: feat

#90 feat/#83-재직자 리스트 조회 API 연결 진행 중
  src/app/search/page.tsx
  src/components/organisms/Main/WorkerInfoContainer/index.tsx
  src/components/organisms/WorkerInfoCard/index.tsx
Labels: feat

#92 feat#81 마이페이지 수정
  .eslintrc.json
  package-lock.json
  package.json
  src/chat/src/components/VideoRoomComponent.js
  src/components/molecules/Input/index.tsx
  src/components/organisms/BasicInfo/index.tsx
  src/types/data.d.ts
Labels: feat

#94 Feat/#93 openvidu list
  src/app/seekerChat/page.tsx
  src/app/workerChat/page.tsx
  src/chat/App.tsx
  src/chat/src/components/VideoRoomComponent.js
  src/chat/src/components/stream/StreamComponent.js
  src/components/organisms/BasicInfo/index.tsx
  src/components/organisms/ChatInfoCard/index.stories.tsx
  src/components/organisms/ChatInfoCard/index.tsx
  src/components/organisms/Login/index.tsx
  src/components/organisms/Signup/index.tsx
  src/components/organisms/TodayChatInfo/index.tsx
  src/components/organisms/WorkerInfoCard/index.tsx
Labels: feat

#95 service worker 404 error
  src/app/layout.tsx
  src/chat/src/registerServiceWorker.js
Labels: bug

#96 hotfix: deployment 주소 수정
  src/chat/src/components/VideoRoomComponent.js
Labels: bug

#98 Feat/#91 SearchInput, FilterModal Component 모달창 열고 닫는 상태 관리 연결
  .storybook/public/assets/icon/icon_business_bag.svg
  public/assets/icon/icon_business_bag.svg
  src/app/login/page.tsx
  src/app/search/page.tsx
  src/app/seekers/edit/page.tsx
  src/app/signup/page.tsx
  src/components/atoms/Icon/index.stories.tsx
  src/components/atoms/Icon/index.tsx
  src/components/molecules/Button/index.stories.tsx
  src/components/molecules/DropdownButton/index.tsx
  src/components/molecules/SearchInput/index.stories.tsx
  src/components/molecules/SearchInput/index.tsx
  src/components/organisms/FilterModal/index.stories.tsx
  src/components/organisms/FilterModal/index.tsx
  src/components/organisms/MentoSearch/index.stories.tsx
  src/components/organisms/MentoSearch/index.tsx
  src/components/templates/LoginSignupLayout/index.tsx
  src/components/templates/MyPageLayout/index.tsx
  src/components/templates/WorkerInfoListLayout/index.tsx
  src/utils/state.ts
Labels: feat

#99 Feat/#91 WorkerInfoCard Component 기능 구현
  src/app/search/page.tsx
  src/app/workers/info/page.tsx
  src/components/molecules/SearchInput/index.tsx
  src/components/organisms/FilterModal/index.stories.tsx
  src/components/organisms/FilterModal/index.tsx
  src/components/organisms/MentoSearch/index.tsx
  src/components/organisms/WorkerInfoCard/index.stories.tsx
  src/components/organisms/WorkerInfoCard/index.tsx
  src/components/templates/WorkerInfoListLayout/index.tsx
  src/utils/state.ts
Labels: feat

#104 Feat/#101 calendar
  src/app/meeting/page.tsx
  src/app/search/page.tsx
  src/app/workers/edit/page.tsx
  src/app/workers/info/page.tsx
  src/components/molecules/Button/SelectButton.tsx
  src/components/molecules/Button/index.stories.tsx
  src/components/molecules/Calendar/index.tsx
  src/components/molecules/SearchInput/index.tsx
  src/components/organisms/BasicInfo/index.tsx
  src/components/organisms/Signup/index.tsx
  src/components/organisms/WorkerInfoCard/index.tsx
  src/components/templates/MeetingLayout/index.tsx
  src/utils/state.ts
Labels: feat

#109 mod/#107-timeformat
  src/app/meeting/page.tsx
Labels: mod

#111 mod/#110-FilterModal에서 적용하기 버튼을 눌렀을 때, 입력 정보 검색되도록 수정
  src/app/search/page.tsx
  src/components/molecules/DropdownButton/index.tsx
  src/components/molecules/SearchInput/index.tsx
  src/components/organisms/FilterModal/index.tsx
  src/components/organisms/WorkerInfoCard/index.tsx
  src/themes/colors.ts
  src/utils/state.ts
Labels: mod

#113 Mod/#112 3d shape 수정
  src/app/workers/edit/page.tsx
  src/components/organisms/AlertContainer/index.tsx
  src/components/templates/LoginSignupLayout/index.tsx
  src/components/templates/MyPageLayout/index.tsx
Labels: mod

#114 mod/#110-재직자 검색 기능 개선
  src/app/search/page.tsx
  src/components/molecules/DropdownButton/index.tsx
  src/components/organisms/FilterModal/index.tsx
  src/components/organisms/MentoSearch/index.tsx
  src/components/organisms/WorkerInfoCard/index.tsx
  src/components/templates/WorkerInfoListLayout/index.tsx
  src/utils/state.ts
Labels: mod

#108 feat/#102-Header기능추가
  README.md
  package-lock.json
  package.json
  src/components/molecules/Button/HyperLinkButton.tsx
  src/components/molecules/Header/index.tsx
  src/components/molecules/SideMenu/index.tsx
Labels: feat

#118 feat: 메인페이지 scroll interaction 적용
  README.md
  package-lock.json
  package.json
  src/components/organisms/Main/ChatInfoContainer/index.tsx
  src/components/organisms/Main/IntroTextContainer/index.tsx
  src/components/organisms/Main/ProcessInfoContainer/index.tsx
  src/components/organisms/Main/PromoteTextContainer/index.tsx
  src/components/organisms/Main/WorkerInfoContainer/index.tsx
  src/containers/AosContainer/index.tsx
Labels: feat

#121 feat/#120 화상채팅 UI 수정
  src/chat/src/components/VideoRoomComponent.css
  src/chat/src/components/chat/ChatComponent.css
  src/chat/src/components/chat/ChatComponent.js
  src/chat/src/components/toolbar/ToolbarComponent.css
  src/chat/src/components/toolbar/ToolbarComponent.js
Labels: feat

#119 feat/#117 hyperlink button animation 추가
  src/app/workers/info/page.tsx
  src/components/molecules/Button/HyperLinkButton.module.css
  src/components/molecules/Button/HyperLinkButton.tsx
  src/components/organisms/TodayChatInfo/index.tsx
Labels: feat

#125 bug/#124 상담요청시간 필수값으로 설정
  src/app/meeting/page.tsx
  src/app/seekerChat/page.tsx
  src/components/molecules/Button/HyperLinkButton.tsx
Labels: bug

#128 bug/#127 workers/edit bug 수정
  src/app/workers/edit/page.tsx
Labels: bug

#130 bug/#129 구직자의 커피챗 리스트에 대기중인 것도 표시
  src/app/seekerChat/page.tsx
  src/components/organisms/ChatInfoCard/index.tsx
Labels: bug

#134 Mod/#115 style
  package-lock.json
  package.json
  src/components/organisms/Main/ChatInfoContainer/index.tsx
  src/components/organisms/Main/IntroTextContainer/index.tsx
  src/components/organisms/Main/ProcessInfoContainer/index.tsx
  src/components/organisms/Main/PromoteTextContainer/index.tsx
  src/components/organisms/Main/WorkerInfoContainer/index.tsx
  src/components/organisms/WorkerInfoCardSlider/index.tsx
  src/components/templates/MainLayout/MainBlackBackgroundLayout/index.tsx
  src/components/templates/MainLayout/MainBlueBackgroundLayout/index.tsx
  src/lib/sweetAlert.tsx
Labels: feat

#137 feat: sweet alert2 lib 생성, 로그아웃 기능 구현
  src/components/molecules/Header/index.tsx
  src/components/molecules/SideMenu/index.tsx
  src/components/organisms/Login/index.tsx
  src/lib/sweetAlert.tsx
Labels: feat

#139 mod: 나의 커피챗 리스트 오버플로우 제거
  src/app/search/page.tsx
  src/app/seekerChat/page.tsx
  src/app/workerChat/page.tsx
  src/components/organisms/AlertContainer/index.tsx
Labels: mod

#141 bug/#140 재직자의 커피챗 리스트에서도 수락 / 거절이 아닌 대기중으로 뜨는 문제 수정
  src/app/seekerChat/page.tsx
  src/app/workerChat/page.tsx
  src/app/workers/info/page.tsx
  src/chat/src/components/VideoRoomComponent.js
  src/components/organisms/ChatInfoCard/index.stories.tsx
  src/components/organisms/ChatInfoCard/index.tsx
Labels: bug

#143 Mod/#135 style
  package-lock.json
  package.json
  src/app/meeting/page.tsx
  src/app/seekerChat/page.tsx
  src/app/workers/edit/page.tsx
  src/app/workers/info/page.tsx
  src/components/molecules/Button/HyperLinkButton.tsx
  src/components/molecules/Header/index.tsx
  src/components/molecules/SideMenu/index.tsx
  src/components/organisms/BasicInfo/index.tsx
  src/components/organisms/Login/index.tsx
  src/components/organisms/Signup/index.tsx
  src/components/templates/MyPageLayout/index.tsx
Labels: feat, mod

#144 bug: recoil 상태 새로고침하면 사라지는 이슈 해결
  package-lock.json
  package.json
  src/app/workers/info/page.tsx
  src/components/templates/LoginSignupLayout/index.tsx
  src/utils/state.ts
Labels: bug

#145 bug/#142 예약 신청 페이지 오류 해결
  src/app/meeting/page.tsx
Labels: bug

#153 mod/#152-재직자 상세정보 수정
  src/app/workers/info/page.tsx
Labels: mod

#156 mod: 재직자 상세 페이지 UI 수정 - 컴포넌트, 텍스트 가운데 정렬
  src/app/workers/info/page.tsx
Labels: mod

#160 mod: 커리업 신청 페이지, 재직자 상세 페이지 구조 수정 / slider dots 제거 / alert 동작 수정
  src/app/meeting/page.tsx
  src/app/workers/edit/page.tsx
  src/app/workers/info/page.tsx
  src/components/organisms/FilterModal/index.tsx
  src/components/organisms/WorkerInfoCardSlider/index.tsx
Labels: mod

#167 feat: 거부된 채팅 리스트 보여주기
  src/app/seekerChat/page.tsx
  src/app/workerChat/page.tsx
  src/components/organisms/ChatInfoCard/index.tsx
Labels: feat

#169 feat: 3d shape floating animation 생성
  src/app/seekerChat/page.tsx
  src/app/workerChat/page.tsx
  src/components/templates/LoginSignupLayout/index.tsx
  src/components/templates/MainLayout/MainBlackBackgroundLayout/index.tsx
  src/components/templates/MainLayout/MainBlueBackgroundLayout/index.tsx
  src/components/templates/MeetingLayout/index.tsx
  src/components/templates/MyPageLayout/index.tsx
  src/components/templates/WorkerInfoListLayout/index.tsx
  src/containers/FloatingContainer/index.tsx
Labels: feat
